import { expect, test } from '@playwright/test';

test('manual selection survives global search and refresh; reveal and export', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /在纸间/ })).toBeVisible();
  await page.screenshot({ path: `test-results/home-${info.project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBeTruthy();
  await page.locator('.mode-card').nth(1).click();
  await page.getByRole('button', { name: '开始洗牌' }).click();
  await expect(page.getByRole('status')).toHaveText('将牌组分成两叠');
  await expect(page.locator('.back-card')).toHaveCount(78);
  await page.getByRole('button', { name: '牌位 1', exact: true }).click();
  await page.getByRole('button', { name: '牌位 78', exact: true }).click();
  await page.screenshot({ path: `test-results/selection-${info.project.name}.png`, fullPage: true });
  await page.getByRole('button', { name: '全站卡牌查询' }).click();
  await page.getByRole('textbox', { name: '搜索卡牌' }).fill('ＴＨＥ ＦＯＯＬ');
  await expect(page.locator('.modal .library-card')).toHaveCount(1);
  await expect.poll(()=>page.locator('.modal .library-card img').evaluate((el:HTMLImageElement)=>el.naturalHeight)).toBe(1200);
  await page.locator('.modal .library-card').click();
  await expect(page.locator('.card-detail h2')).toHaveText('愚者');
  await page.getByRole('button', { name: '返回搜索' }).click();
  await expect(page.getByRole('textbox', { name: '搜索卡牌' })).toHaveValue('ＴＨＥ ＦＯＯＬ');
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await expect(page.locator('.back-card.chosen')).toHaveCount(2);
  await page.reload();
  await expect(page.locator('.back-card.chosen')).toHaveCount(2);
  await page.getByRole('button', { name: '牌位 3', exact: true }).click();
  await page.getByRole('button', { name: '确认选牌' }).click();
  await expect(page.locator('.reading-card')).toHaveCount(3);
  await page.getByRole('button', { name: '翻开过去' }).click();
  await expect(page.locator('.flip-card.is-flipped')).toHaveCount(1);
  await page.getByRole('button', { name: '全部翻开' }).click();
  await expect(page.locator('.flip-card.is-flipped')).toHaveCount(3);
  for(const face of await page.locator('.flip-front img').all()){
    await expect(face).toHaveAttribute('src', /-display-.*\.webp$/);
    await expect.poll(()=>face.evaluate((el:HTMLImageElement)=>el.naturalHeight)).toBeGreaterThanOrEqual(1200);
  }
  await page.getByRole('textbox', { name: '我的笔记' }).fill('测试：这次记录只保存在本设备。');
  await page.getByRole('button', { name: '保存笔记' }).click();
  await expect(page.getByText('笔记已保存')).toBeVisible();
  await page.getByRole('button', { name: '导出分享图' }).click();
  await expect(page.getByRole('checkbox', { name: '包含我的问题' })).not.toBeChecked();
  await page.getByRole('button', { name: '生成预览' }).click();
  await expect(page.getByRole('img', { name: '分享图预览' })).toBeVisible();
  const download = page.waitForEvent('download');
  await page.getByRole('link', { name: '下载 PNG' }).click();
  await (await download).saveAs(`test-results/share-${info.project.name}.png`);
  expect(errors).toEqual([]);
});

test('daily result remains fixed after settings, history deletion and reload', async ({ page }) => {
  await page.goto('/');
  await page.locator('.mode-card').first().click();
  await page.getByRole('button', { name: '快速抽取' }).click();
  await page.getByRole('button', { name: '全部翻开' }).click();
  await expect(page.locator('.flip-card.is-flipped')).toHaveCount(1);
  const first = await page.locator('.reading-copy h3').textContent();
  const orientation = await page.locator('.orientation').textContent();
  const nav = page.locator('.site-header nav:visible, .mobile-nav:visible');
  await nav.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByRole('spinbutton', { name: '逆位概率' }).fill('100');
  await nav.getByRole('button', { name: /记录/ }).click();
  await expect.poll(()=>page.locator('.history-thumbnails img').evaluate((el:HTMLImageElement)=>el.naturalHeight)).toBe(1200);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '删除记录' }).click();
  await nav.getByRole('button', { name: '抽牌', exact: true }).click();
  await expect(page.locator('.reading-copy h3')).toHaveText(first!);
  await page.reload();
  await expect(page.locator('.reading-copy h3')).toHaveText(first!);
  await expect(page.locator('.orientation')).toHaveText(orientation!);
  await page.clock.setSystemTime(new Date(Date.now()+86400000));
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
  await expect(page.getByRole('heading', { name: '给自己，一段安静的时间。' })).toBeVisible();
  await nav.getByRole('button', { name: /图鉴/ }).click();
  await expect(page.locator('.library-card')).toHaveCount(78);
  await expect.poll(()=>page.locator('.library-card img').first().evaluate((el:HTMLImageElement)=>el.naturalHeight)).toBe(1200);
});

test('verified offline pack allows reopening, lookup, quick draw and export offline', async ({ page, context }) => {
  await page.goto('/settings');
  await page.getByRole('button', { name: '下载离线资源' }).click();
  await expect(page.getByText('核心资源已就绪 · 音频已就绪')).toBeVisible({ timeout: 45000 });
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByRole('heading', { name: '按自己的节奏，探索。' })).toBeVisible();
  await page.getByRole('button', { name: '全站卡牌查询' }).click();
  await page.getByRole('textbox', { name: '搜索卡牌' }).fill('权杖八');
  await expect(page.locator('.modal .library-card')).toHaveCount(1);
  await page.locator('.modal .library-card').click();
  await expect(page.locator('.detail-art img')).toBeVisible();
  expect(await page.locator('.detail-art img').evaluate((el: HTMLImageElement) => el.naturalWidth)).toBeGreaterThan(0);
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  const nav = page.locator('.site-header nav:visible, .mobile-nav:visible');
  await nav.getByRole('button', { name: '首页', exact: true }).click();
  await page.locator('.mode-card').last().click();
  await page.getByLabel('抽取数量').selectOption('10');
  await page.getByRole('spinbutton', { name: '逆位概率' }).fill('100');
  await page.getByRole('button', { name: '快速抽取' }).click();
  await expect(page.locator('.reading-card')).toHaveCount(10);
  await expect(page.getByText('离线抽牌 · 已保存到本设备 · 逆位概率 100%')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBeTruthy();
  await page.getByRole('button', { name: '全部翻开' }).scrollIntoViewIfNeeded();
  await page.screenshot({path:'test-results/offline-reading.png'});
  await page.getByRole('button', { name: '全部翻开' }).click();
  await expect(page.locator('.orientation')).toHaveText(Array(10).fill('逆位'));
  await page.getByRole('button', { name: '导出分享图' }).click();
  await page.getByRole('button', { name: '生成预览' }).click();
  await expect(page.getByRole('img', { name: '分享图预览' })).toBeVisible();
  await context.setOffline(false);
});
